version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=elec
      - POSTGRES_USER=elec
      - POSTGRES_DB=elec
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
